# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-12 13:12
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buurt',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('gml_id', models.CharField(max_length=255)),
                ('id', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('naam', models.CharField(blank=True, max_length=255, null=True)),
                ('display', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('uri', models.CharField(blank=True, max_length=255, null=True)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'buurt',
            },
        ),
        migrations.CreateModel(
            name='Buurtcombinatie',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('gml_id', models.CharField(max_length=255)),
                ('id', models.CharField(blank=True, max_length=255, null=True)),
                ('vollcode', models.CharField(blank=True, max_length=255, null=True)),
                ('naam', models.CharField(blank=True, max_length=255, null=True)),
                ('display', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('uri', models.CharField(blank=True, max_length=255, null=True)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('wkb_geometry_simplified', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=0)),
            ],
            options={
                'db_table': 'buurtcombinatie',
            },
        ),
        migrations.CreateModel(
            name='Drukteindex',
            fields=[
                ('index', models.BigIntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('vollcode', models.TextField(blank=True, null=True)),
                ('weekday', models.BigIntegerField(blank=True, null=True)),
                ('hour', models.BigIntegerField(blank=True, null=True)),
                ('alpha_live', models.FloatField(blank=True, null=True)),
                ('alpha_week', models.FloatField(blank=True, null=True)),
                ('gvb_buurt', models.FloatField(blank=True, null=True)),
                ('gvb_stad', models.FloatField(blank=True, null=True)),
                ('verblijversindex', models.FloatField(blank=True, null=True)),
                ('alpha', models.FloatField(blank=True, null=True)),
                ('gvb', models.FloatField(blank=True, null=True)),
                ('drukteindex', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'drukteindex',
            },
        ),
        migrations.CreateModel(
            name='DrukteindexHotspots',
            fields=[
                ('index', models.BigIntegerField(primary_key=True, serialize=False)),
                ('hotspot', models.TextField(blank=True, db_column='Hotspot', null=True)),
                ('hour', models.BigIntegerField(blank=True, null=True)),
                ('drukteindex', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, db_column='Latitude', null=True)),
                ('longitude', models.FloatField(blank=True, db_column='Longitude', null=True)),
            ],
            options={
                'db_table': 'drukteindex_hotspots',
            },
        ),
        migrations.CreateModel(
            name='Functiekaart',
            fields=[
                ('index', models.BigIntegerField(primary_key=True, serialize=False)),
                ('objectnummer', models.BigIntegerField(blank=True, db_column='OBJECTNUMMER', null=True)),
                ('functie2_oms', models.TextField(blank=True, db_column='FUNCTIE2_OMS', null=True)),
                ('zaaknaam', models.TextField(blank=True, db_column='ZAAKNAAM', null=True)),
                ('functie2_eng', models.TextField(blank=True, db_column='FUNCTIE2_ENG', null=True)),
                ('functie1_id', models.TextField(blank=True, db_column='FUNCTIE1_ID', null=True)),
                ('functie1_oms', models.TextField(blank=True, db_column='FUNCTIE1_OMS', null=True)),
                ('functie1_eng', models.TextField(blank=True, db_column='FUNCTIE1_ENG', null=True)),
                ('functie2_id', models.TextField(blank=True, db_column='FUNCTIE2_ID', null=True)),
                ('laag', models.BigIntegerField(blank=True, db_column='LAAG', null=True)),
                ('adressen_lijst', models.TextField(blank=True, db_column='ADRESSEN_LIJST', null=True)),
                ('adressen_vot', models.TextField(blank=True, db_column='ADRESSEN_VOT', null=True)),
                ('adressen_aantal', models.BigIntegerField(blank=True, db_column='ADRESSEN_AANTAL', null=True)),
                ('oppervlakte_som', models.BigIntegerField(blank=True, db_column='OPPERVLAKTE_SOM', null=True)),
                ('oppervlakte_nul', models.BigIntegerField(blank=True, db_column='OPPERVLAKTE_NUL', null=True)),
                ('checkdatum', models.TextField(blank=True, db_column='CHECKDATUM', null=True)),
                ('zaak_id', models.BigIntegerField(blank=True, db_column='ZAAK_ID', null=True)),
                ('coords', models.TextField(blank=True, db_column='COORDS', null=True)),
                ('lng', models.TextField(blank=True, db_column='LNG', null=True)),
                ('lat', models.TextField(blank=True, db_column='LAT', null=True)),
                ('unnamed_19', models.FloatField(blank=True, db_column='Unnamed: 19', null=True)),
            ],
            options={
                'db_table': 'FUNCTIEKAART',
            },
        ),
        migrations.CreateModel(
            name='Gebiedsgerichtwerken',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('gml_id', models.CharField(max_length=255)),
                ('id', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('naam', models.CharField(blank=True, max_length=255, null=True)),
                ('display', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('uri', models.CharField(blank=True, max_length=255, null=True)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'gebiedsgerichtwerken',
            },
        ),
        migrations.CreateModel(
            name='Google',
            fields=[
                ('index', models.BigIntegerField(primary_key=True, serialize=False)),
                ('location', models.TextField(blank=True, db_column='Location', null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('historical', models.FloatField(blank=True, null=True)),
                ('live', models.FloatField(blank=True, null=True)),
                ('place_id', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('types', models.TextField(blank=True, null=True)),
                ('differences', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=0)),
            ],
            options={
                'db_table': 'google',
            },
        ),
        migrations.CreateModel(
            name='GoogleDec',
            fields=[
                ('index', models.BigIntegerField(primary_key=True, serialize=False)),
                ('place_id', models.TextField(blank=True, null=True)),
                ('historical', models.FloatField(blank=True, null=True)),
                ('live', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('types', models.TextField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=0)),
            ],
            options={
                'db_table': 'google_dec',
            },
        ),
        migrations.CreateModel(
            name='GoogleDecWithBc',
            fields=[
                ('index', models.BigIntegerField(primary_key=True, serialize=False)),
                ('place_id', models.TextField(blank=True, null=True)),
                ('historical', models.FloatField(blank=True, null=True)),
                ('live', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('types', models.TextField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=0)),
                ('vollcode', models.CharField(blank=True, max_length=255, null=True)),
                ('naam', models.CharField(blank=True, max_length=255, null=True)),
                ('stadsdeel_code', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'google_dec_with_bc',
            },
        ),
        migrations.CreateModel(
            name='GoogleWithBc',
            fields=[
                ('index', models.BigIntegerField(primary_key=True, serialize=False)),
                ('location', models.TextField(blank=True, db_column='Location', null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('historical', models.FloatField(blank=True, null=True)),
                ('live', models.FloatField(blank=True, null=True)),
                ('place_id', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('types', models.TextField(blank=True, null=True)),
                ('differences', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=0)),
                ('vollcode', models.CharField(blank=True, max_length=255, null=True)),
                ('naam', models.CharField(blank=True, max_length=255, null=True)),
                ('stadsdeel_code', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'google_with_bc',
            },
        ),
        migrations.CreateModel(
            name='Gvb',
            fields=[
                ('index', models.BigIntegerField(primary_key=True, serialize=False)),
                ('halte', models.TextField(blank=True, null=True)),
                ('incoming', models.BigIntegerField(blank=True, null=True)),
                ('outgoing', models.BigIntegerField(blank=True, null=True)),
                ('day_numeric', models.BigIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=0)),
            ],
            options={
                'db_table': 'gvb',
            },
        ),
        migrations.CreateModel(
            name='GvbWithBc',
            fields=[
                ('index', models.BigIntegerField(primary_key=True, serialize=False)),
                ('halte', models.TextField(blank=True, null=True)),
                ('incoming', models.BigIntegerField(blank=True, null=True)),
                ('outgoing', models.BigIntegerField(blank=True, null=True)),
                ('day_numeric', models.BigIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=0)),
                ('vollcode', models.CharField(blank=True, max_length=255, null=True)),
                ('naam', models.CharField(blank=True, max_length=255, null=True)),
                ('stadsdeel_code', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gvb_with_bc',
            },
        ),
        migrations.CreateModel(
            name='Stadsdeel',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('gml_id', models.CharField(max_length=255)),
                ('id', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('naam', models.CharField(blank=True, max_length=255, null=True)),
                ('display', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('uri', models.CharField(blank=True, max_length=255, null=True)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'stadsdeel',
            },
        ),
        migrations.CreateModel(
            name='Tellus',
            fields=[
                ('index', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tellus_id', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('meetwaarde', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=0)),
            ],
            options={
                'db_table': 'tellus',
            },
        ),
        migrations.CreateModel(
            name='TellusWithBc',
            fields=[
                ('index', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tellus_id', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('meetwaarde', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=0)),
                ('vollcode', models.CharField(blank=True, max_length=255, null=True)),
                ('naam', models.CharField(blank=True, max_length=255, null=True)),
                ('stadsdeel_code', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tellus_with_bc',
            },
        ),
        migrations.CreateModel(
            name='Verblijversindex',
            fields=[
                ('index', models.BigIntegerField(primary_key=True, serialize=False)),
                ('wijk', models.TextField(blank=True, null=True)),
                ('oppervlakte_m2', models.FloatField(blank=True, null=True)),
                ('verblijversindex', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'VERBLIJVERSINDEX',
            },
        ),
    ]
