# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Melding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subrubriek', models.CharField(default='empty', max_length=255)),
                ('beschrijving', models.CharField(default='empty', max_length=255)),
                ('lat', models.CharField(default='empty', max_length=255)),
                ('lng', models.CharField(default='empty', max_length=255)),
            ],
        ),
    ]
