# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoonmonitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LengteGewicht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lengte', models.CharField(max_length=255)),
                ('Gewicht', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Melding',
        ),
    ]
