# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-05 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citydynamics', '0002_auto_20171026_1540'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LengteGewicht',
        ),
    ]
